# Generated by Django 3.1.6 on 2021-02-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orederId',
            new_name='orderId',
        ),
    ]
